node names: ["porta", "baxter", "bancada", "bancada dupla", "mesa"]
nodes to explore: [0, 1, 4]
human seconds to move: 5

graph nodes astro points:
    - [0.0, 0.0]
    - [0.5, 0.5]
    - [1.0, 1.0]
    - [1.0, 0.0]
    - [0.5, 1.0]

graph nodes real world points:
  - [0.0, 0.0]
  - [0.5, 0.5]
  - [1.0, 1.0]
  - [1.0, 0.0]
  - [0.5, 1.0]

homography:

  camera frame points:
  - [82, 339]
  - [105, 545]
  - [367, 274]
  - [446, 446]
  - [611, 225]
  - [709, 372]

  real world points:
    - [0, 0]
    - [0, 1]
    - [1, 0]
    - [1, 1]
    - [2, 0]
    - [2, 1]

color segmentation:
  hue: [25, 60]
  sat: [35, 255]
  val: [80, 255]