# Done
node names: ["porta", "meio da sala", "baxter", "mesa miguel", "mesa joao"]
nodes to explore: [0, 1, 4]
human seconds to move: 5

graph nodes astro points:
  - []

# Done
graph nodes camera points:
  - [332, 565]
  - [621, 354]
  - [153, 314]
  - [982, 189]
  - [1032, 380]

# Done
homography:

  # Done
  camera frame points:
  - [82, 339]
  - [105, 545]
  - [367, 274]
  - [446, 446]
  - [611, 225]
  - [709, 372]

  # Done
  real world points:
    - [0, 0]
    - [0, 1]
    - [1, 0]
    - [1, 1]
    - [2, 0]
    - [2, 1]

# Done
color segmentation:
  hue: [24, 78]
  sat: [0, 255]
  val: [161, 245]