node names: ["porta", "baxter", "bancada", "bancada dupla", "mesa"]
nodes to explore: [0, 1, 4]
human seconds to move: 5

graph nodes astro points:
  - [0.50, 1.150]
  - [1.61, 0.756]
  - [0.40, 0.19]
  - [3.10, 0.29]
  - [3.48, 1.286]

graph nodes camera points:
  - [295, 527]
  - [587, 357]
  - [211, 343]
  - [860, 211]
  - [1060, 323]

homography:

  camera frame points:
  - [82, 339]
  - [105, 545]
  - [367, 274]
  - [446, 446]
  - [611, 225]
  - [709, 372]

  real world points:
    - [0, 0]
    - [0, 1]
    - [1, 0]
    - [1, 1]
    - [2, 0]
    - [2, 1]

color segmentation:
  #hue: [25, 60]
  #sat: [35, 255]
  #val: [80, 255]
  hue: [38, 67]
  sat: [32, 255]
  val: [156, 255]