# Done
node names: ["door", "middle of the room", "baxter", "Table Michael", "Table John"]
nodes to explore: [1, 2, 4]
initial state: [0, 0, 0, 0, 0]
human seconds to move: 10

graph nodes astro points:
  - [0, 0]
  - [0, 1]
  - [0, 2]
  - [0, 3]
  - [0, 4]

# Done
graph nodes camera points:
  - [234, 624]
  - [626, 360]
  - [194, 314]
  - [1005, 133]
  - [1115,  266]

# Done
homography:

  # Done
  camera frame points:
  - [82, 339]
  - [105, 545]
  - [367, 274]
  - [446, 446]
  - [611, 225]
  - [709, 372]

  # Done
  real world points:
    - [0, 0]
    - [0, 1]
    - [1, 0]
    - [1, 1]
    - [2, 0]
    - [2, 1]

# Done
color segmentation:
  hue: [24, 78]
  sat: [0, 255]
  val: [161, 245]